-- MySQL Script generated by MySQL Workbench
-- Wed Aug 23 12:04:04 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema btl
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema btl
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `btl` ;
USE `btl` ;

-- -----------------------------------------------------
-- Table `btl`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `btl`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) CHARACTER SET 'utf8mb3' NOT NULL,
  `description` VARCHAR(50) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8;


-- -----------------------------------------------------
-- Table `btl`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `btl`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) CHARACTER SET 'utf8mb3' NOT NULL,
  `last_name` VARCHAR(45) CHARACTER SET 'utf8mb3' NOT NULL,
  `email` VARCHAR(45) CHARACTER SET 'utf8mb3' NOT NULL,
  `phone` VARCHAR(45) CHARACTER SET 'utf8mb3' NOT NULL,
  `username` VARCHAR(45) CHARACTER SET 'utf8mb3' NOT NULL,
  `password` VARCHAR(100) CHARACTER SET 'utf8mb3' NOT NULL,
  `active` BIT(1) NOT NULL,
  `user_role` VARCHAR(45) CHARACTER SET 'utf8mb3' NOT NULL,
  `image` VARCHAR(45) COLLATE 'utf8mb3_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2;


-- -----------------------------------------------------
-- Table `btl`.`sale_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `btl`.`sale_order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(10,0) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `sale_order_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `btl`.`user` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `btl`.`shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `btl`.`shop` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8mb3' NOT NULL,
  `description` VARCHAR(45) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `shop_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `btl`.`user` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `btl`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `btl`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `shop_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `name` VARCHAR(45) CHARACTER SET 'utf8mb3' NOT NULL,
  `description` VARCHAR(45) CHARACTER SET 'utf8mb3' NOT NULL,
  `price` DECIMAL(10,0) NOT NULL,
  `manufacturer` VARCHAR(45) CHARACTER SET 'utf8mb3' NOT NULL,
  `image` VARCHAR(200) CHARACTER SET 'utf8mb3' NOT NULL,
  `created_date` DATETIME NOT NULL,
  `active` BIT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `shop_id_idx` (`shop_id` ASC) VISIBLE,
  INDEX `category_id_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `btl`.`category` (`id`),
  CONSTRAINT `shop_id`
    FOREIGN KEY (`shop_id`)
    REFERENCES `btl`.`shop` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `btl`.`order_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `btl`.`order_detail` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `unit_price` DECIMAL(10,0) NULL DEFAULT NULL,
  `num` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `order_id_idx` (`order_id` ASC) VISIBLE,
  INDEX `product_id_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `btl`.`sale_order` (`id`),
  CONSTRAINT `product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `btl`.`product` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `btl`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `btl`.`tag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) COLLATE 'utf8mb3_unicode_ci' NULL DEFAULT NULL,
  `tagcol` VARCHAR(45) COLLATE 'utf8mb3_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `btl`.`prod_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `btl`.`prod_tag` (
  `id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `product_id_idx` (`product_id` ASC) VISIBLE,
  INDEX `tag_id_idx` (`tag_id` ASC) VISIBLE,
  CONSTRAINT `prod_tag_ibfk_1`
    FOREIGN KEY (`product_id`)
    REFERENCES `btl`.`product` (`id`),
  CONSTRAINT `prod_tag_ibfk_2`
    FOREIGN KEY (`tag_id`)
    REFERENCES `btl`.`tag` (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
